title: 'GA4GH - DUO'
label: 'GA4GH::DURI'
tagline: 'A Workstream of the Global Alliance for Genomics and Health'
description: |
  DURI represents the data use requirements & conditions workstream of the Global Alliance for Genomics and Health
keywords:
  - genomics
  - Beacon
  - DNA
  - GA4GH
  - DUO
site_domain_name: "ga4gh-duri.github.io"
url: "http://ga4gh-duri.github.io"
email: ga4gh-data-use-subgroup@ga4gh.org
github_organisation: ebispot

# instructions for processing specific directories

include:        # usually only pages in / and /_posts are "seen" => processed
  - categories  # contains landing pages for each category
  - tags        # contains landing pages for each tag

# Collections are used to organise pages into logical groups; these do not need 
# to have a relation to the "categories", though this is highly recommended
# Collection directories reside in "/collections_dir/_(collection name)".

collections:
   #news:
   #  output: true
   #  permalink: /news/:path/
  # people:
   #  output: true
   #  permalink: /people/:path/
  documentation:
    output: true
    permalink: /documentation/:path/
  # howto:
  #   output: true
  #   permalink: /howto/:path/
  welcome:
    output: true
    permalink: /welcome/:path/
  minutes:
    output: true
    permalink: /minutes/:path/
# optional; here, all collections are inside "/pages"
# if used, also the standard "_posts" directory has to be moved there!
collections_dir: pages  

# navigation blocks can be used to separate different categories and add e.g. 
# external link block(s), in combination with a properly modified layout

nav_cat_blocks: # comma-separated "label,type,label_visibility"
  General: 'General,categories,hide'
  related_sites: 'Related Sites,related_sites,show'
  
categories_year_sorted:
  - news
  - minutes

General:
   #news: News
   #people: Participants
  documentation: Documentation
  howto# : 'Examples, Guides & FAQ'
  welcome: 'Examples, Guides & FAQ'
  minutes: 'Meeting minutes'
  contact: Contacts

related_sites: 
  'GA4GH::Discovery': 'http://ga4gh-discovery.github.io'
  'GA4GH::CP': 'http://ga4gh-cp.github.io'
  'GA4GH::GKS': 'http://ga4gh-gks.github.io'
  'SchemaBlocks': 'http://schemablocks.org'
  GA4GH: 'http://www.ga4gh.org'

# tag_cloud items

cloud_tags:
  - CP
  - Discovery
  - GA4GH
  - GKS
  - code
  - admins
  - contacts
  - contributors
  - developers
  - leads
  - press

# additional Jekyll instructions

plugins:
 - jekyll-seo-tag
type: website
show_downloads: true
future: true
safe: false
navigation_max_items: 4 # number of shown links in current category
emptyArray: []          # dummy element for array initialisation
